openapi: 3.0.2
info:
  title: SystemAPI-consommation-services
  description: Toute opération liée à la gestion des consommation exposés par REDAL
  contact:
    name: Indra % Minsait
    url: http://www.minsait.com
    email: XXXXXXXXXX@minsait.com
  version: 1.0.0
servers:
 -
  url: https://gatewayadd-dev.onesaitplatform.com/redal-consommation-services/v1
  description: DEV
 -
  url: https://gatewayadd-uat.onesaitplatform.com/redal-consommation-services/v1
  description: UAT
 -
  url: https://pro-host/redal-consommation-services/v1
  description: PRO

security:
 -
  default: []
tags:
 -
  name: rsu-consommation-requete
paths:
  /consommation:
    get:
      tags:
       - rsu-consommation-requete
      summary: Il s'agit d'une fonction qui permet de récupérer la liste des consommations ou bien les consommations dont l’année est supérieur a 2020
      description: Ce service permet de récupérer la liste des consommations ou bien les consommations dont l’année est supérieur a 2020
      operationId: get-consommation-donnees
      parameters:
       -
        $ref: '#/components/parameters/x-client-id'
       -
        $ref: '#/components/parameters/x-request-id'
       -
        $ref: '#/components/parameters/x-request-application-name'
       -
        $ref: '#/components/parameters/codeAller'
       -
        $ref: '#/components/parameters/idcs'
       -
        $ref: '#/components/parameters/cnie'
       -
        $ref: '#/components/parameters/dateDebut'
       -
        $ref: '#/components/parameters/dateFin'
       -
        $ref: '#/components/parameters/cil'
       -
        $ref: '#/components/parameters/commune'
      responses:
        "103":
          description: Premiers indices
        "200":
          description: La demande envoyée par le client a été traitée correctement.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/consommation'
        "204":
          description: Pas de contenu
        "400":
          description: La syntaxe de la requête n'a pas été comprise par le serveur
        "401":
          description: La demande nécessite une authentification de l'utilisateur
        "403":
          description: Le serveur a refusé d'exécuter la demande
        "404":
          description: Le document ou fichier demandé par le client est introuvable.
        "405":
          description: Méthode Non Autorisée
        "426":
          description: Mise a niveau  requise
        "440":
          description: Délai de connexion
        "500":
          description: Internal Server Error
        "501":
          description: Not Implemented
        "505":
          description: 'La version http insupportable '
        "529":
          description: Le site est surchargé
      security:
       -
        ApiKeyAuth: []
       -
        bearerAuth: []
       -
        oAuthWSO2: []
       -
        default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
components:
  schemas:
    consommation:
      required:
       - consommation
      type: object
      properties:
        consommation:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            required:
             - cnie
             - codeRetour
             - commune
             - complementAdresse
             - immeuble
             - nomPrenom
             - prefecture
             - quartier
             - sousQuartier
            properties:
              codeRetour:
                minLength: 1
                type: string
              cnie:
                minLength: 1
                type: string
              nomPrenom:
                minLength: 1
                type: string
              prefecture:
                type: number
              commune:
                type: number
              quartier:
                type: number
              sousQuartier:
                type: number
              immeuble:
                type: number
              complementAdresse:
                minLength: 1
                type: string
              listeConsommations:
                minItems: 1
                uniqueItems: true
                type: array
                items:
                  required:
                   - année
                   - mois
                   - montantEau
                   - montantElectricite
                  properties:
                    mois:
                      type: number
                    année:
                      type: number
                    montantEau:
                      type: number
                    montantElectricite:
                      type: number
              listeConsommationAutresRésidences:
                minItems: 1
                uniqueItems: true
                type: array
                items:
                  required:
                   - adresse
                   - année
                   - cil
                   - commune
                   - mois
                   - montantEau
                   - montantElectricite
                  properties:
                    cil:
                      type: number
                    adresse:
                      minLength: 1
                      type: string
                    commune:
                      type: number
                    mois:
                      type: number
                    année:
                      type: number
                    montantEau:
                      type: number
                    montantElectricite:
                      type: number
      x-examples:
        example-1:
          consommation:
           -
            codeRetour: "987845454"
            cnie: "56"
            nomPrenom: douma amine
            prefecture: 45
            commune: 12
            quartier: 65
            sousQuartier: 658
            immeuble: 6
            complementAdresse: oulfa casablanca
            listeConsommations:
             -
              mois: 3
              année: 2021
              montantEau: 250
              montantElectricite: 300
            listeConsommationAutresRésidences:
             -
              cil: 4589
              adresse: oulfa casablanca
              commune: 12
              mois: 3
              année: 2021
              montantEau: 250
              montantElectricite: 350
  parameters:
    codeAller:
      name: codeAller
      in: query
      description: 'Identifiant unique de l’enregistrement  '
      required: true
      style: form
      explode: true
      schema:
        type: number
    idcs:
      name: idcs
      in: query
      description: 'Identifiant digital civil et social du citoyen '
      required: true
      style: form
      explode: true
      schema:
        type: number
    cnie:
      name: cnie
      in: query
      description: 'Numéro de la carte d’identité  '
      required: true
      style: form
      explode: true
      schema:
        type: string
    dateDebut:
      name: dateDebut
      in: query
      description: Date de début
      required: true
      style: form
      explode: true
      schema: {}
    dateFin:
      name: dateFin
      in: query
      description: Date de fin
      required: true
      style: form
      explode: true
      schema: {}
    cil:
      name: cil
      in: query
      description: Référence local de consommation
      required: true
      style: form
      explode: true
      schema:
        type: number
    commune:
      name: commune
      in: query
      description: Commune de la résidence
      required: true
      style: form
      explode: true
      schema:
        type: number
    x-client-id:
      name: X-Client-ID
      in: header
      description: ID d'API de l'application source
      required: true
      style: simple
      explode: false
      schema:
        type: string
    x-request-application-name:
      name: X-Request-Application-Name
      in: header
      description: Description Nom de l'application source
      required: true
      style: simple
      explode: false
      schema:
        type: string
    x-request-id:
      name: X-Request-ID
      in: header
      description: ID de demande (ID de corrélation)
      required: true
      style: simple
      explode: false
      schema:
        type: string
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: client_id
      in: header
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    oAuthWSO2:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://api.example.com/oauth2/authorize
          scopes: {}
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: ""
          scopes: {}
x-wso2-auth-header: Authorization
x-wso2-cors:
  corsConfigurationEnabled: true
  accessControlAllowOrigins:
   - '*'
  accessControlAllowCredentials: false
  accessControlAllowHeaders:
   - authorization
   - Access-Control-Allow-Origin
   - Content-Type
   - SOAPAction
   - apikey
   - testKey
   - X-Request-Application-Name
   - X-Request-ID
   - X-Client-ID
  accessControlAllowMethods:
   - GET
   - PUT
   - POST
   - DELETE
   - PATCH
   - OPTIONS
x-wso2-production-endpoints:
  urls:
   - http://localhost:3000/redal-consommation-services/v1
  type: http
x-wso2-sandbox-endpoints:
  urls:
   - http://localhost:3000/redal-consommation-services/v1
  type: http
x-wso2-basePath: /redal-consommation-services/v1
x-wso2-transports:
 - http
 - https
x-wso2-response-cache:
  enabled: false
  cacheTimeoutInSeconds: 300
